<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <home-summary/>
    <page-body>
      <div id="home-news-container">
        <home-news/>
        <home-config-section v-if="config.home.title != null"
          :title="config.home.title" :body="config.home.body"/>
      </div>
      <project-list/>
    </page-body>
    <whats-new/>

    <!-- VG: TOTP Optional Enrollment Prompt -->
    <vg-totp-enrollment-prompt-modal v-if="currentUser.dataExists"
      :state="showOptionalEnrollmentModal" :user-id="currentUser.id"
      @hide="hideOptionalEnrollmentModal" @setup="startTotpSetup"/>
    <vg-totp-setup-modal v-if="currentUser.dataExists"
      :state="showTotpSetupModal" :user-id="currentUser.id"
      @hide="hideTotpSetupModal" @success="handleTotpSetupSuccess"/>
  </div>
</template>

<script setup>
import { defineAsyncComponent, inject, ref, onMounted } from 'vue';

import HomeNews from './home/news.vue';
import HomeSummary from './home/summary.vue';
import PageBody from './page/body.vue';
import ProjectList from './project/list.vue';
import WhatsNew from './whats-new.vue';
import VgTotpEnrollmentPromptModal from './vg/vg-totp-enrollment-prompt-modal.vue';
import VgTotpSetupModal from './vg/vg-totp-setup-modal.vue';

import useProjects from '../request-data/projects';
import { useRequestData } from '../request-data';
import { loadAsync } from '../util/load-async';
import { noop } from '../util/util';

defineOptions({
  name: 'Home'
});

const HomeConfigSection = defineAsyncComponent(loadAsync('HomeConfigSection'));

const projects = useProjects();
projects.request({ url: '/v1/projects?forms=true&datasets=true' }).catch(noop);

const config = inject('config');
const { currentUser } = useRequestData();

// VG: TOTP enrollment modal state
const showOptionalEnrollmentModal = ref(false);
const showTotpSetupModal = ref(false);

// VG: Check for pending enrollment prompt on mount
// Note: Mandatory enrollment is handled on the login page, not here
onMounted(() => {
  const pendingPrompt = sessionStorage.getItem('pendingTotpEnrollmentPrompt');

  if (pendingPrompt === 'true') {
    // Clear the flag
    sessionStorage.removeItem('pendingTotpEnrollmentPrompt');
    // Show optional enrollment prompt modal
    showOptionalEnrollmentModal.value = true;
  }
});

// VG: Modal event handlers
const hideOptionalEnrollmentModal = () => {
  showOptionalEnrollmentModal.value = false;
};

const startTotpSetup = () => {
  // Hide enrollment prompt modal
  showOptionalEnrollmentModal.value = false;
  // Show TOTP setup modal
  showTotpSetupModal.value = true;
};

const hideTotpSetupModal = () => {
  showTotpSetupModal.value = false;
};

const handleTotpSetupSuccess = () => {
  // Setup completed successfully
  showTotpSetupModal.value = false;
  // Optionally refresh user data to reflect new TOTP status
  if (currentUser.dataExists) {
    currentUser.request({ url: '/v1/users/current' }).catch(noop);
  }
};
</script>

<style lang="scss">
@import '../assets/scss/variables';

#home-news-container {
  display: flex;
  > * { flex: 1; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "heading": [
      "Welcome to Central."
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "heading": [
      "Vítejte v Centralu."
    ]
  },
  "de": {
    "heading": [
      "Willkommen bei Central"
    ]
  },
  "es": {
    "heading": [
      "Bienvenido a Central."
    ]
  },
  "fr": {
    "heading": [
      "Bienvenue sur Central"
    ]
  },
  "id": {
    "heading": [
      "Selamat datang di Central."
    ]
  },
  "it": {
    "heading": [
      "Benvenuto su Central"
    ]
  },
  "pt": {
    "heading": [
      "Bem-vindo ao Central."
    ]
  },
  "sw": {
    "heading": [
      "Karibu Central"
    ]
  },
  "zh": {
    "heading": [
      "欢迎使用Central。"
    ]
  },
  "zh-Hant": {
    "heading": [
      "歡迎來到 Central."
    ]
  }
}
</i18n>
